[main]

# to use .ini file
securityManager.realms = $iniRealm



# -----------------------------------------------------------------------------
# Users and their assigned roles
#
# Each line conforms to the format defined in the
# org.apache.shiro.realm.text.TextConfigurationRealm#setUserDefinitions JavaDoc
# -----------------------------------------------------------------------------

[users]
# user = password, role1, role2, role3, ...


sven = pass, admin_role, org.apache.causeway.applib.services.sudo.SudoService#accessAll
dick = pass, simple_role, default_role
bob  = pass, simple_role, default_role, fixtures_role
joe  = pass, simple_role, default_role
guest = guest, guest_role, default_role



# -----------------------------------------------------------------------------
# Roles with assigned permissions
#
# Each line conforms to the format defined in the
# org.apache.shiro.realm.text.TextConfigurationRealm#setRoleDefinitions JavaDoc
# -----------------------------------------------------------------------------

[roles]
# role = perm1, perm2, perm3, ...
# perm in format: logicalTypeNamespace:logicalTypeSimpleName:memberName:r,w

admin_role     = *
guest_role     = app.pets:PetOwners:findByName:*,\
                 app.pets:PetOwners:listAll:*,\
                 app.pets:*:*:r
default_role   = causeway.applib,\
                 causeway.security
conf_role      = causeway.conf
h2_role        = causeway.ext.h2Console
features_role  = causeway.feat
schema_role    = causeway.schema
sudo_role      = causeway.sudo
fixtures_role  = causeway.testing.fixtures
jdo_role       = causeway.persistence.jdo
swagger_role   = causeway.viewer.roRendering
